const plans={
  money:{title:'Money first. Start with clarity, not panic.',steps:['Today: list the exact balance, deadline, and what changed. Save it in one note.','Within 24 hours: use the REACH for Yourself hub to identify emergency-aid and scholarship routes.','Within 72 hours: email financial aid or your student-success office using the message below.'],message:'Hi, I am currently facing an urgent financial barrier that may affect my enrollment. Can we meet this week to discuss emergency aid, payment options, or any campus support I may qualify for?'},
  food:{title:'Basic needs are academic support.',steps:['Today: check the REACH for Yourself hub for food, housing, hygiene, and emergency support routes.','Within 24 hours: contact your campus basic-needs, dean of students, or student-success office.','Within 72 hours: make one plan for this week: meals, transportation, and a safe place to sleep.'],message:'Hi, I am dealing with an urgent basic-needs situation and would appreciate a confidential conversation about food, housing, or emergency support available to students.'},
  school:{title:'One hard class does not decide your future.',steps:['Today: write down the class, grade, assignment dates, and the professor’s office hours.','Within 24 hours: send a short email requesting a meeting and contact tutoring or advising.','Within 72 hours: make a recovery plan with only the next three academic tasks.'],message:'Hi Professor, I want to be proactive about my progress in this course. Could I meet with you during office hours or another time this week to discuss the best steps I can take from here?'},
  mind:{title:'You deserve support before you are at your limit.',steps:['Today: tell one trusted person you are having a hard time. You do not have to explain everything.','Within 24 hours: find your campus counseling, wellness, or student-support office through the REACH hub.','If you may hurt yourself or are in immediate danger, call 911. Call or text 988 for the Suicide & Crisis Lifeline.'],message:'Hi, I am a student who has been feeling overwhelmed and I would like to know what confidential support or appointment options are available.'},
  friend:{title:'You do not have to have the perfect words.',steps:['Today: send one direct, caring check-in: “I noticed you seem stressed. I am here with you.”','Within 24 hours: ask what kind of support would feel helpful — listening, food, a ride, or finding help.','If they are in immediate danger, call 911. For crisis support in the U.S., call or text 988.'],message:'I care about you. You do not have to carry this alone. Can we talk today about one thing that would make the next 24 hours easier?'},
  ride:{title:'Logistics should not end your semester.',steps:['Today: name the barrier: transportation, childcare, work schedule, or all three.','Within 24 hours: check the REACH hub and your campus student-support office for emergency options.','Within 72 hours: ask one advisor or support office about flexibility, local partners, and help you can use now.'],message:'Hi, a transportation/childcare barrier is affecting my ability to stay on track. Could you help me understand any student supports, referrals, or flexibility options available?' }
};
const output=document.getElementById('plan-output');
document.querySelectorAll('[data-need]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-need]').forEach(b=>b.classList.remove('active'));button.classList.add('active');const p=plans[button.dataset.need];output.innerHTML=`<div class="plan-card"><h3>${p.title}</h3><ol>${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol><a href="https://estherfundsfoundation.org/reach-yourself" target="_blank" rel="noopener">Open REACH resources ↗</a><details><summary>Copy a message to ask for help</summary><p>${p.message}</p><button class="copy-message">Copy message</button></details></div>`;const c=output.querySelector('.copy-message');c.addEventListener('click',()=>{navigator.clipboard.writeText(p.message);c.textContent='Copied ✓';setTimeout(()=>c.textContent='Copy message',1500)});}));
